#! /bin/sh

killall lemonbar
pgrep -x sxhkd > /dev/null || sxhkd &
#picom --no-fading-openclose &
setxkbmap pt
xsetroot -cursor_name left_ptr

feh --bg-fill --randomize ~/Documents/Wallpapers/* &
#feh --bg-fill --randomize $HOME/Documents/AI\ pape/* &
#feh --bg-fill --randomize ~/Documents/Animu/*
#feh --bg-fill ~/Images/pape.jpg

# Vertical Screen configuration
#xrandr --output HDMI-A-1 --rotate left; xrandr --output DisplayPort-0 --mode 1920x1080 -r 119.99; xrandr --output DisplayPort-0 --mode 1920x1080 -r 143.99 --right-of HDMI-A-1 --mode 1920x1080
#bash $HOME/Scripts/lemonbar.sh | lemonbar -p -B \#80000000 -F \#FFFFFF -g 980x25+50+10 -n MyBar &

# Regular Double Screen configuration
xrandr --output DisplayPort-0 --mode 1920x1080 -r 119.99; xrandr --output DisplayPort-0 --mode 1920x1080 -r 143.99 --right-of HDMI-A-1 --mode 1920x1080
bash $HOME/Scripts/lemonbar.sh | lemonbar -p -B \#80000000 -F \#FFFFFF -g 1800x25+50+10 -n MyBar &

bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X 

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.50
#bsspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
