#! /bin/sh

killall lemonbar
pgrep -x sxhkd > /dev/null || sxhkd &
#picom --no-fading-openclose &
feh --bg-fill --randomize ~/Documents/Wallpapers/* &
#feh --bg-fill --randomize ~/Documents/Animu/*
setxkbmap pt
xsetroot -cursor_name left_ptr
xrandr --output DisplayPort-0 --mode 1920x1080 -r 119.99; xrandr --output DisplayPort-0 --mode 1920x1080 -r 143.99 --right-of HDMI-A-1 --mode 1920x1080
bash /home/jorgeveloso/lemonbar.sh | lemonbar -p -B \#0000000 -g 1800x50+50 -n MyBar &

bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X 

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.50
#bsspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
